name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
    - working-directory: ./backend
      run: cargo build --verbose
    - name: Run tests
    - working-directory: ./backend
      run: cargo test --verbose
